name: forge2d_game
description: "Flutter i/o 2024 codelabs."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  characters: ^1.3.0
  flame: ^1.18.0
  flame_forge2d: ^0.18.1
  flutter:
    sdk: flutter
  flutter_soloud: ^2.1.0
  logging: ^1.2.0
  xml: ^6.5.0

dev_dependencies:
  equatable: ^2.0.5
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tiles/
    - assets/audio/music/
    - assets/audio/sfx/
